### ISSUE TITLE
Is this still alive?

### ISSUE THREAD

**Issue by benoror** [ciena-blueplanet/ember-cli-istanbul#2]

**Comment by sglanzer-fire** [comment]
We've offered the name to https://github.com/kategengler/ember-cli-code-coverage which handles Istanbul integration

**Comment by job13er** [comment]
So, no. It's no longer alive. I've updated the `README.md` to point to `ember-cli-code-coverage` and added a `postinstall` script that will tell anyone who tries to install this to use that instead.
